kind: wasmer.io/App.v0
name: beta
owner: dexter404
package: sha256:1fc0cca06ccb5565d6f7ef4cae2f1309e67e2d3c0cdb0ab53dfa04379b072841
debug: true
capabilities:
  database:
    engine: mysql
volumes:
- name: wp-content
  mount: /app/wp-content
scaling:
  mode: single_concurrency
