kind: wasmer.io/App.v0
name: beta
owner: dexter404
package: sha256:24895ab8ddc76d6adc5557133ee3ec0c1691f0edbc0796db5070dc19178a1981
capabilities:
  instaboot:
    requests:
    - path: /
      headers:
      - name: Accept
        value: text/html
      - name: Accept-Language
        value: en-US
    - path: /
      headers:
      - name: Accept
        value: text/html
      - name: Accept-Language
        value: en-US
    - path: /
      headers:
      - name: Accept
        value: text/html
      - name: Accept-Language
        value: en-US
    - path: /
      headers:
      - name: Accept
        value: text/html
      - name: Accept-Language
        value: en-US
    max_age: '59m'
  database:
    engine: mysql
volumes:
- name: wp-content
  mount: /app/wp-content
scaling:
  mode: single_concurrency
